### ISSUE TITLE
Add readings to online schedule based on Spring 2022 run; add links to slides+recording based on spreadsheet in Shared with Students for Jan 13 (recur after)

### ISSUE THREAD

**Issue by thomason-jesse** [csci566-spring2023/csci566-spring2023.github.io#2]

**Comment by tejas1995** [comment]
I added the readings and slides link for week 1. Do you want me to also add the readings for Week 2, or all the readings right now itself? Also is there a link for the recording (I don't see a spreadsheet in Shared with Students)

**Comment by tejas1995** [comment]
I think it makes sense to populate the whole Lectures page with readings + milestones, and just updated slides+recording link every week (I think this is what you originally wanted me to do, but my brain is slow)

**Comment by thomason-jesse** [comment]
Yeah, that makes sense to me. We can always adjust future dates if things change on the syllabus.

**Comment by tejas1995** [comment]
Updated: https://csci566-spring2023.github.io/lectures/
